### ISSUE TITLE
Administration area verification fails

### ISSUE THREAD

**Issue by zbylo76** [glhd/laravel-addressing#1]
When you try to use verification area, you ends up with an exception:

> FatalErrorException
> Class 'CommerceGuys\Addressing\Repository\SubdivisionRepository' not found.

It seems like file "SubdivisionRepository.php" referenced in the "AdministrativeAreaRepository.php" at the  line 6 as
`use CommerceGuys\Addressing\Repository\SubdivisionRepository;`
doesn't exists.

**Comment by jgrossi** [comment]
hey thanks for sharing. it seems the addressing package changed namespaces on version 1.0.0. I'm gonna force a lower version for now and then update ours later to match the new namespaces. thanks!

**Comment by jgrossi** [comment]
@zbylo76 the last `commerceguys/addressing` package version is `v.0.8.4`, not `v1.0.*` (the beta one). The namespace has changed only in `1.0.*`. How did you install `galahad/laravel-addressing` package? Why are you getting a newer version of `commerceguys/addressing`?

**Comment by zbylo76** [comment]
@jgrossi you're right. I forgot that I modified you module because I required changes introduced into `commerceguys/addressing` package in the branch `v1.0.*`.
At the end I used `commerceguys/addressing` directly

**Comment by jgrossi** [comment]
@zbylo76 ok! thanks for sharing! ;-)

**Comment by inxilpro** [comment]
@zbylo76 Take a look at https://github.com/glhd/laravel-addressing/tree/v0.5
