### ISSUE TITLE
country_code validation rule produces 500 error when an array is given

### ISSUE THREAD

**Issue by suth** [glhd/laravel-addressing#11]
I was writing some feature tests to ensure that my app handles unexpected input gracefully, and I noticed that if I send an array in place of the country code I get a 500 response instead of 422. This happens because of the call `strtoupper()` on the input [here](https://github.com/glhd/laravel-addressing/blob/master/src/LaravelAddressing.php#L81). I'd be happy to create a PR with some tests and a fix but thought I'd go ahead an open an issue.

Here's a simplified recreation of my feature test failing:
```php
// Inside my test
$this->json('POST', '/api/v1/order', [
    'country_code' => ['this', 'is', 'an', 'array']
])->assertStatus(422);

// Using these validation rules causes 500
'country_code' => ['required', 'string', 'country_code'],

// My temporary workaround using 'bail'
'country_code' => ['required', 'string', 'bail', 'country_code'],
```

**Comment by inxilpro** [comment]
Thanks! You’re definitely welcome to submit a PR.
