### ISSUE TITLE
Declaration of Galahad\LaravelAddressing\Collection\CountryCollection::pop()

### ISSUE THREAD

**Issue by seabasss** [glhd/laravel-addressing#32]
Hello,

I'm getting this after updating to latest Laravel:

`Declaration of Galahad\LaravelAddressing\Collection\CountryCollection::pop(): ?Galahad\LaravelAddressing\Entity\Country must be compatible with Illuminate\Support\Collection::pop($count = 1) `

Here's the pull request and changelog:
https://github.com/laravel/framework/pull/38093
https://github.com/laravel/framework/blob/8.x/CHANGELOG-8.x.md#added

Would it be possible to patch the pop and shift methods? Thank you!

**Comment by inxilpro** [comment]
This will be addressed in version 3.0.0 (which mostly just drops support for older Laravel and PHP versions—no other major changes).

**Comment by seabasss** [comment]
Cool! When is v3 released? Thank you!

**Comment by inxilpro** [comment]
It's out now :)

**Comment by seabasss** [comment]
Sweet, thank you! Worked like a charm!
